services:
  targets-controller:
    image: onlyspans.targets-controller
    build:
      context: .
      dockerfile: src/Onlyspans.TargetsController/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8080"
    profiles:
      - api
      - all
